using System;

namespace VenueBookingSystem.Features.Bookings.DTOs
{
    // ╔══════════════════════════════════════════════════════════════════════╗
    // ║          📜 BOOKING HISTORY ENTRY — ONE LINE IN THE LOGBOOK         ║
    // ║  Every time a booking's STATUS changes, we record it here.          ║
    // ║  Think: like a paper trail — "Who changed what, when, and why?"     ║
    // ║                                                                      ║
    // ║  'record' = immutable — once a history entry is created,            ║
    // ║             it cannot be modified (history should never be edited!)  ║
    // ╚══════════════════════════════════════════════════════════════════════╝
    public record BookingHistoryEntry(
        // 🔢 Unique ID for this history log entry (auto-generated by database)
        int HistoryId,

        // 🔗 Which booking did this status change happen to?
        int BookingId,

        // ⬅️ What was the status BEFORE the change? (e.g. "Pending")
        string OldStatus,

        // ➡️ What is the status AFTER the change? (e.g. "Confirmed")
        string NewStatus,

        // 🕐 Exact date and time when this status change happened
        DateTime ChangedAt,

        // 👤 Who made this change? (e.g. "admin1" or "System")
        string ChangedBy,

        // 📝 Why was it changed? (e.g. "Approved by Priya", "Cancelled by customer")
        string Remarks
    );
}
